import { useMutation, useQuery } from '@tanstack/react-query'
import { useEffect, useState } from 'react'
import { createFileRoute, useNavigate } from '@tanstack/react-router'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Plus, Users } from 'lucide-react'
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from '@/components/ui/card'

// API call to create a room with code generated by the API
async function createRoomApi() {
  const response = await fetch(`${import.meta.env.VITE_API_URL}/api/rooms`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
  })
  if (!response.ok) {
    throw new Error('Failed to create room')
  }
  return response.json()
}

async function fetchRoomByCode(code: string) {
  const response = await fetch(
    `${import.meta.env.VITE_API_URL}/api/rooms/code/${code}`,
  )
  if (!response.ok) {
    throw new Error('Room not found')
  }
  return response.json()
}

export const Route = createFileRoute('/')({
  component: App,
})

const lines = [
  'Start a room. Start a conversation. Start something.',
  'Your circle, your room, your rules.',
  'Spin up a room and let the chatter begin.',
  'Gather your people. We’ll handle the room.',
  'Instantiate a room. Connect instantly.',
  'Private channels. Public vibes optional.',
  'Open a room and bring your people in.',
  'Where your conversations find their space.',
  'Rooms made for conversations that matter.',
  'Create or join a private room to start chatting with your people.',
]

function App() {
  const [line, setLine] = useState(lines[0])

  const navigate = useNavigate()

  const connectRoom = (roomId: string, code: string) => {
    navigate({ to: `/rooms/${roomId}?code=${code}` })
  }

  const mutation = useMutation({
    mutationFn: () => createRoomApi(),
    onSuccess: (data) => {
      connectRoom(data.id, data.code)
    },
  })
  // For joining rooms, keep code state
  const [joinCode, setJoinCode] = useState('')
  const { data, refetch, isFetching, isError, error } = useQuery({
    queryKey: ['room-by-code', joinCode],
    queryFn: () => fetchRoomByCode(joinCode),
    enabled: false,
    retry: false,
  })

  const handleCreateSubmit = (e: React.FormEvent) => {
    e.preventDefault()
    mutation.mutate()
  }

  const handleJoinSubmit = async (e: React.FormEvent) => {
    e.preventDefault()
    if (joinCode.trim()) {
      await refetch()
    }
  }

  useEffect(() => {
    if (data?.id) {
      connectRoom(data.id, data.code)
    }
  }, [data, navigate])

  useEffect(() => {
    const interval = setInterval(() => {
      setLine((prev) => {
        const currentIndex = lines.indexOf(prev)
        const nextIndex = (currentIndex + 1) % lines.length
        return lines[nextIndex]
      })
    }, 8000)
    return () => clearInterval(interval)
  }, [])

  return (
    <div className="relative flex flex-col items-center justify-center min-h-[calc(100vh-4rem)] px-6 py-12 bg-background overflow-hidden">
      <div className="relative w-full max-w-md space-y-8 z-10">
        <div className="text-center space-y-3">
          <h1 className="text-4xl font-extrabold tracking-tight lg:text-5xl">
            Anonymous Maximus
          </h1>
          <p
            key={line}
            className="text-muted-foreground text-lg animate-fade-in-up"
          >
            {line}
          </p>
        </div>
        <div className="grid gap-6">
          <Card className="border shadow-lg overflow-hidden group hover:border-primary/50 transition-all">
            <CardHeader className="pb-4">
              <CardTitle className="text-xl flex items-center gap-2">
                <Users className="w-5 h-5 text-primary" />
                Join a Room
              </CardTitle>
              <CardDescription>
                Enter a 6-character code to enter
              </CardDescription>
            </CardHeader>
            <CardContent>
              <form onSubmit={handleJoinSubmit} className="flex gap-2">
                <Input
                  placeholder="e.g. AB12CD"
                  value={joinCode}
                  onChange={(e) => setJoinCode(e.target.value.toUpperCase())}
                  className="font-mono tracking-widest uppercase"
                  maxLength={6}
                />
                <Button type="submit" disabled={isFetching || !joinCode.trim()}>
                  {isFetching ? 'Joining...' : 'Join'}
                </Button>
              </form>
              {isError && (
                <p className="text-xs text-destructive mt-2 font-medium">
                  {(error as Error).message}
                </p>
              )}
            </CardContent>
          </Card>

          <div className="relative">
            <div className="absolute inset-0 flex items-center">
              <span className="w-full border-t" />
            </div>
            <div className="relative flex justify-center text-xs uppercase">
              <span className="bg-background px-2 text-muted-foreground">
                Or
              </span>
            </div>
          </div>

          <Button
            variant="outline"
            size="lg"
            className="w-full h-16 text-lg border hover:bg-primary hover:text-primary-foreground transition-all gap-2 shadow-sm"
            onClick={handleCreateSubmit}
            disabled={mutation.isPending}
          >
            <Plus className="w-5 h-5" />
            {mutation.isPending ? 'Creating...' : 'Create New Room'}
          </Button>

          {mutation.isError && (
            <p className="text-sm text-destructive text-center font-medium">
              Error: {(mutation.error as Error).message}
            </p>
          )}
        </div>
      </div>
    </div>
  )
}
